### PR TITLE
Added databaseNamePrefix

### PR DESCRIPTION
**Pull request by ppozeti**
Added an optional parameter to Create methods so users can define their own database prefix name.

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
Awesome! thanks a lot 🙏 will publish in a moment

**Comment by Zaid-Ajaj** [comment]
Done 🚀

**Comment by ppozeti** [comment]
hey @Zaid-Ajaj 
I haven't seen the new version being published over nuget, could you please check that? thanks!

**Comment by Zaid-Ajaj** [comment]
Hi @ppozeti this was my bad 😓 I only published the postgres version and forgot the MSSSQL one. I published it now as of v1.2.0 and it will be available in a moment

**Pull request merged**
