### PR TITLE
support MySql

### PR DESCRIPTION
**Pull request by MihailsKuzmins**
Hey @Zaid-Ajaj,
for one of my projects I needed to use MySQL (migrate from SQL server to MySQL). I was using your lib for the SQL server, so I decided that it could be a nice addition to your lib. If it's ok, could you please review the PR :wink:?
Still haven't tested it in the real world, but hopefully my unit tests cover all the cases. At least for now.
Below is a little summary of what I've done.

- create a MySQL ThrowawayDb
- create and restore "snapshots" (MySQL does not seem to provide a build-in functionality for snapshots, therefore, it was solved as backups which are also cleared when `Dispose` is called)
- added tests for MySQL
- updated NuGet packages
- created a VS solution file to combine all projects

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
Hi there @MihailsKuzmins, this is really awesome stuff 🚀 I had it on my to-do list for a while actually. At a first glance, the code looks good, I need to take a deep dive later and try to run the tests locally (I don't have a MySql server locally so I need to install one but that should be alright)

**Comment by MihailsKuzmins** [comment]
@Zaid-Ajaj,

it's great that I could implement something you had planned :zany_face:
However, there is one thing I don't really like about the whole project, namely, code duplication. For all three implementations the base private functions are almost identical. So I was thinking about creating a base project (not as a NuGet package) for `public abstract class ThrowawayDbBase` and `public interface IThrowawayDb`, but it's a subject of another issue, not this one.
(if you find it valid of course :relaxed:)

**Comment by Zaid-Ajaj** [comment]
Hi @MihailsKuzmins I just published v1.0 of ThrowawayDb.MySql 🎉 :fire: 🚀 

Do you have a twitter handle? So that I can talk about and give you the credits 😉 

> However, there is one thing I don't really like about the whole project, namely, code duplication

I understand this point in the sense that it makes the project _clean_ but personally I think each implementation is so little code, it doesn't need that extra bit of organisation and I like to avoid abstractions when I can get away with it hahah

**Comment by MihailsKuzmins** [comment]
@Zaid-Ajaj,
thank you for publishing the new package. I do look forward to using it :rocket:.
My twitter is https://twitter.com/KuzminsMihails, but I don't use it often. I think I created it to complete my stackoverflow account 😄.

Well, I do agree with you. This project is not soo huge as LinqToDb, Dapper or FluentMigratior.
Let's keep thinks simple 😃.

**Comment by Zaid-Ajaj** [comment]
You should use it more often to share with tech twitter about the cool stuff you build, gain exposure and usually get feedback for it 😉

**Comment by MihailsKuzmins** [comment]
> You should use it more often to share with tech twitter about the cool stuff you build, gain exposure and usually get feedback for it 😉

I think you have a point. I will make my first tweet for my Moq extension library 🚀

**Pull request merged**
